#!/usr/bin/env bash

# Function to handle signals
cleanup() {
    echo "Cleaning up and terminating..."
    rm /var/run/myscript.pid
    exit 0
}

# Trap signals and call cleanup function
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; cleanup' SIGTERM SIGQUIT

# Create PID file
echo $$ > /var/run/myscript.pid

# Infinite loop displaying messages
while true; do
    echo "To infinity and beyond"
    sleep 2
done
