#!/usr/bin/env bash

# Function to display usage message
usage() {
    echo "Usage: $0 {start|stop|restart}"
}

# Function to start the process
start_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "Process already running with PID $(<"/var/run/my_process.pid")"
    else
        echo $$ > /var/run/my_process.pid
        echo "manage_my_process started"
        while true; do
            echo "I am alive!" >> /tmp/my_process
            sleep 2
        done
    fi
}

# Function to stop the process
stop_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "manage_my_process stopped"
        rm /var/run/my_process.pid
    else
        echo "Process is not running"
    fi
}

# Function to restart the process
restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

# Check for valid arguments
if [ $# -ne 1 ]; then
    usage
    exit 1
fi

# Perform action based on the argument passed
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        usage
        exit 1
        ;;
esac

exit 0
