#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash"
# Not allowed to use ps
# Get the PID and process name of processes containing the word "bash"

grep -l bash
