#!/usr/bin/env bash
# This script displays "Best SChool" 10 times using a for loop

# Loop through 10 iterations and print "Best School" each time
for ((i = 0; i < 10; i++)); do
	echo "Best School"
done
