#!/usr/bin/env bash
# This script reads and displays information from the /etc/passwd file

# Read the /etc/passwd file line by line
while IFS=: read -r username _ uid _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd
