#!/usr/bin/env bash
# This script tells a story based on the /etc/passwd file

# Set the Internal Field Separator (IFS) to ':'
IFS=":"

# Read the /etc/passwd file line by line
while read -r username _ uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $gecos"
done < /etc/passwd
