#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

# Initialize a counter
count=0

# Loop using while until count reaches 10
while [ $count -lt 10 ]; do
	echo "Best School"
	((count++)) # Increment the counter
done
