#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

# Initialize a counter
count=0

# Loop using until count reaches 10
until [ $count -ge 10 ]; do
	echo "Best School"
	((count++))
done
