#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables for hours and minutes
hour=0
minute=1

# Loop to display hours and minutes
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
    done
    minute=1  # Reset minute counter
    ((hour++))
done
