#!/usr/bin/env bash
# This script configures the local machine's IP settings.

# Update localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts

# Update facebook.com to resolve to 8.8.8.8
sudo sed -i 's/facebook.com/8.8.8.8 facebook.com/g' /etc/hosts
